using SantaMonicaApp.Models;
using Newtonsoft.Json;

namespace SantaMonicaApp.Views;
public partial class StreetsDetails : ContentPage, IQueryAttributable
{
    private HttpClient _httpClient;
    List<Address> streetNumbers;
	public StreetsDetails()
	{
		InitializeComponent();

        _httpClient = new HttpClient();
        //httpClient.BaseAddress = new Uri("");
    }

    public void ApplyQueryAttributes(IDictionary<string, object> query)
    {
        var selectedStreet = query["SelectedStreet"] as string;
        GetAllStreetsAsync(selectedStreet);
        ListNumbers.ItemsSource = streetNumbers;
    }

    private async void GetAllStreetsAsync(string selectedStreet)
    {
        streetNumbers = new List<Address>()
        {
             new Address { Id = 1, Name = "Acacia Parida 01", Email = "", Owner = "", Phone = "", Extensions = "199,200" },
             new Address { Id = 2, Name = "Acacia Parida 02", Email = "", Owner = "", Phone = "", Extensions = "201,202" },
             new Address { Id = 3, Name = "Acacia Parida 03", Email = "", Owner = "", Phone = "", Extensions = "203,204" },
             new Address { Id = 4, Name = "Acacia Parida 04", Email = "", Owner = "", Phone = "", Extensions = "205,206" },
             new Address { Id = 5, Name = "Acacia Parida 05", Email = "", Owner = "", Phone = "", Extensions = "207,208" },
             new Address { Id = 6, Name = "Acacia Parida 06", Email = "", Owner = "", Phone = "", Extensions = "209,210" },
             new Address { Id = 7, Name = "Acacia Parida 07", Email = "", Owner = "", Phone = "", Extensions = "211,212" },
             new Address { Id = 8, Name = "Acacia Parida 08", Email = "", Owner = "", Phone = "", Extensions = "213,214" },
             new Address { Id = 9, Name = "Acacia Parida 09", Email = "", Owner = "", Phone = "", Extensions = "215,216" },
             new Address { Id = 10, Name = "Acacia Parida 10", Email = "", Owner = "", Phone = "", Extensions = "217,218,219" },
             new Address { Id = 11, Name = "Acacia Parida 11", Email = "", Owner = "", Phone = "", Extensions = "220,221" },
             new Address { Id = 12, Name = "Acacia Parida 12", Email = "", Owner = "", Phone = "", Extensions = "222,223" },
             new Address { Id = 13, Name = "Acacia Parida 13", Email = "", Owner = "", Phone = "", Extensions = "224,225" },
             new Address { Id = 14, Name = "Acacia Parida 14", Email = "", Owner = "", Phone = "", Extensions = "226,227" },
             new Address { Id = 15, Name = "Acacia Parida 15", Email = "", Owner = "", Phone = "", Extensions = "228,229" },
             new Address { Id = 16, Name = "Acacia Parida 16", Email = "", Owner = "", Phone = "", Extensions = "230,231" },
             new Address { Id = 17, Name = "Acacia Parida 17", Email = "", Owner = "", Phone = "", Extensions = "232,233" },
             new Address { Id = 18, Name = "Acacia Parida 18", Email = "", Owner = "", Phone = "", Extensions = "234,235" },
             new Address { Id = 19, Name = "Acacia Parida 19", Email = "", Owner = "", Phone = "", Extensions = "236,237" },
             new Address { Id = 20, Name = "Acacia Parida 20", Email = "", Owner = "", Phone = "", Extensions = "238,239" },
             new Address { Id = 21, Name = "Acacia Parida 21", Email = "", Owner = "", Phone = "", Extensions = "240,241" },
             new Address { Id = 22, Name = "Acacia Parida 22", Email = "", Owner = "", Phone = "", Extensions = "242,243" },
             new Address { Id = 23, Name = "Acacia Parida 23", Email = "", Owner = "", Phone = "", Extensions = "244,245" },
             new Address { Id = 24, Name = "Acacia Parida 24", Email = "", Owner = "", Phone = "", Extensions = "246,247" },
             new Address { Id = 25, Name = "Acacia Parida 25", Email = "", Owner = "", Phone = "", Extensions = "248,249" },
             new Address { Id = 26, Name = "Acacia Parida 26", Email = "", Owner = "", Phone = "", Extensions = "250,251" },
             new Address { Id = 27, Name = "Acacia Parida 27", Email = "", Owner = "", Phone = "", Extensions = "252,253" },
             new Address { Id = 28, Name = "Acacia Parida 28", Email = "", Owner = "", Phone = "", Extensions = "254,255" },
             new Address { Id = 29, Name = "Acacia Parida 30", Email = "", Owner = "", Phone = "", Extensions = "256,257" },
             new Address { Id = 30, Name = "Acacia Parida 32", Email = "", Owner = "", Phone = "", Extensions = "258,259" },
             new Address { Id = 31, Name = "Acacia Parida 33", Email = "", Owner = "", Phone = "", Extensions = "260,261" },
             new Address { Id = 32, Name = "Acacia Parida 34", Email = "", Owner = "", Phone = "", Extensions = "262,263" },
             new Address { Id = 33, Name = "Acacia Parida 35", Email = "", Owner = "", Phone = "", Extensions = "264,265" },
             new Address { Id = 34, Name = "Acacia Parida 36", Email = "", Owner = "", Phone = "", Extensions = "266,267" },
             new Address { Id = 35, Name = "Acacia Parida 37", Email = "", Owner = "", Phone = "", Extensions = "268,269" },
             new Address { Id = 36, Name = "Acacia Parida 38", Email = "", Owner = "", Phone = "", Extensions = "270,271" },
             new Address { Id = 37, Name = "Acacia Parida 39", Email = "", Owner = "", Phone = "", Extensions = "272,273" },
             new Address { Id = 38, Name = "Acacia Parida 40", Email = "", Owner = "", Phone = "", Extensions = "274,275" },
             new Address { Id = 39, Name = "Acacia Parida 41", Email = "", Owner = "", Phone = "", Extensions = "276,277" },
             new Address { Id = 40, Name = "Acacia Parida 42", Email = "", Owner = "", Phone = "", Extensions = "278,279" },
             new Address { Id = 41, Name = "Acacia Parida 43", Email = "", Owner = "", Phone = "", Extensions = "280,281" },
             new Address { Id = 42, Name = "Acacia Parida 44", Email = "", Owner = "", Phone = "", Extensions = "282,283" },
             new Address { Id = 43, Name = "Acacia Parida 45", Email = "", Owner = "", Phone = "", Extensions = "284,285" },
             new Address { Id = 44, Name = "Acacia Parida 46", Email = "", Owner = "", Phone = "", Extensions = "286,287" },
             new Address { Id = 45, Name = "Acacia Parida 47", Email = "", Owner = "", Phone = "", Extensions = "288,289" },
             new Address { Id = 46, Name = "Acacia Parida 48", Email = "", Owner = "", Phone = "", Extensions = "290,291" },
             new Address { Id = 47, Name = "Acacia Parida 49", Email = "", Owner = "", Phone = "", Extensions = "291,293" },
             new Address { Id = 48, Name = "Acacia Parida 50", Email = "", Owner = "", Phone = "", Extensions = "294,295" },
             new Address { Id = 49, Name = "Acacia Parida 51", Email = "", Owner = "", Phone = "", Extensions = "296,297" },
             new Address { Id = 50, Name = "Acacia Parida 52", Email = "", Owner = "", Phone = "", Extensions = "298,299" },
             new Address { Id = 51, Name = "Acacia Parida 53", Email = "", Owner = "", Phone = "", Extensions = "300,301" },
             new Address { Id = 52, Name = "Acacia Parida 54", Email = "", Owner = "", Phone = "", Extensions = "302,303" },
             new Address { Id = 53, Name = "Acacia Parida 55", Email = "", Owner = "", Phone = "", Extensions = "304,305" },
             new Address { Id = 54, Name = "Acacia Parida 56", Email = "", Owner = "", Phone = "", Extensions = "306,307" },
             new Address { Id = 55, Name = "Acacia Parida 57", Email = "", Owner = "", Phone = "", Extensions = "308,309" },
             new Address { Id = 56, Name = "Acacia Parida 58", Email = "", Owner = "", Phone = "", Extensions = "310,311" },
             new Address { Id = 57, Name = "Acacia Parida 59", Email = "", Owner = "", Phone = "", Extensions = "312,313" },
             new Address { Id = 58, Name = "Acacia Parida 60", Email = "", Owner = "", Phone = "", Extensions = "314,315" },
             new Address { Id = 59, Name = "Acacia Parida 62", Email = "", Owner = "", Phone = "", Extensions = "316,317" },
             new Address { Id = 60, Name = "Genoveses 01", Email = "", Owner = "", Phone = "", Extensions = "628,629" },
             new Address { Id = 61, Name = "Genoveses 02", Email = "", Owner = "", Phone = "", Extensions = "630,631" },
             new Address { Id = 62, Name = "Genoveses 03", Email = "", Owner = "", Phone = "", Extensions = "632,633" },
             new Address { Id = 63, Name = "Genoveses 04", Email = "", Owner = "", Phone = "", Extensions = "634,635" },
             new Address { Id = 64, Name = "Genoveses 05", Email = "", Owner = "", Phone = "", Extensions = "636,637" },
             new Address { Id = 65, Name = "Genoveses 06", Email = "", Owner = "", Phone = "", Extensions = "638,639" },
             new Address { Id = 66, Name = "Genoveses 07", Email = "", Owner = "", Phone = "", Extensions = "640,641" },
             new Address { Id = 67, Name = "Genoveses 08", Email = "", Owner = "", Phone = "", Extensions = "642,643" },
             new Address { Id = 68, Name = "Genoveses 09", Email = "", Owner = "", Phone = "", Extensions = "644,645" },
             new Address { Id = 69, Name = "Genoveses 10", Email = "", Owner = "", Phone = "", Extensions = "646,647" },
             new Address { Id = 70, Name = "Genoveses 11", Email = "", Owner = "", Phone = "", Extensions = "648,649" },
             new Address { Id = 71, Name = "Genoveses 12", Email = "", Owner = "", Phone = "", Extensions = "650,651" },
             new Address { Id = 72, Name = "Genoveses 13", Email = "", Owner = "", Phone = "", Extensions = "653,654" },
             new Address { Id = 73, Name = "Genoveses 14", Email = "", Owner = "", Phone = "", Extensions = "655,656" },
             new Address { Id = 74, Name = "Genoveses 15", Email = "", Owner = "", Phone = "", Extensions = "657,658" },
             new Address { Id = 75, Name = "Genoveses 16", Email = "", Owner = "", Phone = "", Extensions = "659,660" },
             new Address { Id = 76, Name = "Genoveses 17", Email = "", Owner = "", Phone = "", Extensions = "661,662" },
             new Address { Id = 77, Name = "Genoveses 18", Email = "", Owner = "", Phone = "", Extensions = "663,664,665" },
             new Address { Id = 78, Name = "Genoveses 19", Email = "", Owner = "", Phone = "", Extensions = "666,667" },
             new Address { Id = 79, Name = "Genoveses 20", Email = "", Owner = "", Phone = "", Extensions = "668,669" },
             new Address { Id = 80, Name = "Genoveses 21", Email = "", Owner = "", Phone = "", Extensions = "670,671" },
             new Address { Id = 81, Name = "Genoveses 22", Email = "", Owner = "", Phone = "", Extensions = "672,673" },
             new Address { Id = 82, Name = "Genoveses 23", Email = "", Owner = "", Phone = "", Extensions = "674,675" },
             new Address { Id = 83, Name = "Genoveses 24", Email = "", Owner = "", Phone = "", Extensions = "676,677" },
             new Address { Id = 84, Name = "Genoveses 25", Email = "", Owner = "", Phone = "", Extensions = "678,679" },
             new Address { Id = 85, Name = "Genoveses 26", Email = "", Owner = "", Phone = "", Extensions = "680,681" },
             new Address { Id = 86, Name = "Genoveses 28", Email = "", Owner = "", Phone = "", Extensions = "682,683" },
             new Address { Id = 87, Name = "Genoveses 29", Email = "", Owner = "", Phone = "", Extensions = "684,685" },
             new Address { Id = 88, Name = "Genoveses 30", Email = "", Owner = "", Phone = "", Extensions = "686,687" },
             new Address { Id = 89, Name = "Genoveses 31", Email = "", Owner = "", Phone = "", Extensions = "688,689" },
             new Address { Id = 90, Name = "Genoveses 32", Email = "", Owner = "", Phone = "", Extensions = "690,691" },
             new Address { Id = 91, Name = "Genoveses 33", Email = "", Owner = "", Phone = "", Extensions = "692,693" },
             new Address { Id = 92, Name = "Genoveses 34", Email = "", Owner = "", Phone = "", Extensions = "694,695" },
             new Address { Id = 93, Name = "Genoveses 35", Email = "", Owner = "", Phone = "", Extensions = "696,697" },
             new Address { Id = 94, Name = "Genoveses 36", Email = "", Owner = "", Phone = "", Extensions = "698,699" },
             new Address { Id = 95, Name = "Genoveses 37", Email = "", Owner = "", Phone = "", Extensions = "700,701" },
             new Address { Id = 96, Name = "Genoveses 38", Email = "", Owner = "", Phone = "", Extensions = "702,703" },
             new Address { Id = 97, Name = "Genoveses 39", Email = "", Owner = "", Phone = "", Extensions = "704,705" },
             new Address { Id = 98, Name = "Genoveses 40", Email = "", Owner = "", Phone = "", Extensions = "706,707" },
             new Address { Id = 99, Name = "Genoveses 41", Email = "", Owner = "", Phone = "", Extensions = "708,709" },
             new Address { Id = 100, Name = "Genoveses 42", Email = "", Owner = "", Phone = "", Extensions = "710,711" },
             new Address { Id = 101, Name = "Genoveses 43", Email = "", Owner = "", Phone = "", Extensions = "712,713" },
             new Address { Id = 102, Name = "Genoveses 44", Email = "", Owner = "", Phone = "", Extensions = "714,715" },
             new Address { Id = 103, Name = "Genoveses 45", Email = "", Owner = "", Phone = "", Extensions = "716,717" },
             new Address { Id = 104, Name = "Genoveses 46", Email = "", Owner = "", Phone = "", Extensions = "718,719" },
             new Address { Id = 105, Name = "Genoveses 47", Email = "", Owner = "", Phone = "", Extensions = "720,721" },
             new Address { Id = 106, Name = "Genoveses 48", Email = "", Owner = "", Phone = "", Extensions = "722,723" },
             new Address { Id = 107, Name = "Genoveses 49", Email = "", Owner = "", Phone = "", Extensions = "724,725" },
             new Address { Id = 108, Name = "Genoveses 50", Email = "", Owner = "", Phone = "", Extensions = "726,727" },
             new Address { Id = 109, Name = "Genoveses 51", Email = "", Owner = "", Phone = "", Extensions = "728,729" },
             new Address { Id = 110, Name = "Genoveses 52", Email = "", Owner = "", Phone = "", Extensions = "730,731" },
             new Address { Id = 111, Name = "Genoveses 53", Email = "", Owner = "", Phone = "", Extensions = "732,733" },
             new Address { Id = 112, Name = "Genoveses 54", Email = "", Owner = "", Phone = "", Extensions = "734,735" },
             new Address { Id = 113, Name = "Eolo 02", Email = "", Owner = "", Phone = "", Extensions = "462,463" },
             new Address { Id = 114, Name = "Eolo 04", Email = "", Owner = "", Phone = "", Extensions = "464,465" },
             new Address { Id = 115, Name = "Eolo 06", Email = "", Owner = "", Phone = "", Extensions = "466,467" },
             new Address { Id = 116, Name = "Eolo 08", Email = "", Owner = "", Phone = "", Extensions = "468,469" },
             new Address { Id = 117, Name = "Eolo 10", Email = "", Owner = "", Phone = "", Extensions = "470,471" },
             new Address { Id = 118, Name = "Eolo 12", Email = "", Owner = "", Phone = "", Extensions = "472,473" },
             new Address { Id = 119, Name = "Eolo 14", Email = "", Owner = "", Phone = "", Extensions = "474,475" },
             new Address { Id = 120, Name = "Eolo 16", Email = "", Owner = "", Phone = "", Extensions = "476,477" },
             new Address { Id = 121, Name = "Eolo 18", Email = "", Owner = "", Phone = "", Extensions = "478,479" },
             new Address { Id = 122, Name = "Eolo 20", Email = "", Owner = "", Phone = "", Extensions = "480,481" },
             new Address { Id = 123, Name = "Eolo 22", Email = "", Owner = "", Phone = "", Extensions = "482,483" },
             new Address { Id = 124, Name = "Eolo 24", Email = "", Owner = "", Phone = "", Extensions = "484,485" },
             new Address { Id = 125, Name = "Eolo 26", Email = "", Owner = "", Phone = "", Extensions = "486,487" },
             new Address { Id = 126, Name = "Eolo 27", Email = "", Owner = "", Phone = "", Extensions = "" },
             new Address { Id = 127, Name = "Eolo 28", Email = "", Owner = "", Phone = "", Extensions = "488,489" },
             new Address { Id = 128, Name = "Eolo 29", Email = "", Owner = "", Phone = "", Extensions = "490,491,492" },
             new Address { Id = 129, Name = "Eolo 30", Email = "", Owner = "", Phone = "", Extensions = "493,494" },
             new Address { Id = 130, Name = "Eolo 31", Email = "", Owner = "", Phone = "", Extensions = "495,496" },
             new Address { Id = 131, Name = "Eolo 32", Email = "", Owner = "", Phone = "", Extensions = "497,498" },
             new Address { Id = 132, Name = "Eolo 33", Email = "", Owner = "", Phone = "", Extensions = "499,500" },
             new Address { Id = 133, Name = "Eolo 34", Email = "", Owner = "", Phone = "", Extensions = "501,502" },
             new Address { Id = 134, Name = "Eolo 35", Email = "", Owner = "", Phone = "", Extensions = "503,504" },
             new Address { Id = 135, Name = "Eolo 36", Email = "", Owner = "", Phone = "", Extensions = "505,506" },
             new Address { Id = 136, Name = "Eolo 37", Email = "", Owner = "", Phone = "", Extensions = "507,508" },
             new Address { Id = 137, Name = "Eolo 38", Email = "", Owner = "", Phone = "", Extensions = "509,510" },
             new Address { Id = 138, Name = "Eolo 39", Email = "", Owner = "", Phone = "", Extensions = "511,512" },
             new Address { Id = 139, Name = "Eolo 40", Email = "", Owner = "", Phone = "", Extensions = "513,514" },
             new Address { Id = 140, Name = "Eolo 41", Email = "", Owner = "", Phone = "", Extensions = "515,516" },
             new Address { Id = 141, Name = "Eolo 42", Email = "", Owner = "", Phone = "", Extensions = "517,518" },
             new Address { Id = 142, Name = "Eolo 43", Email = "", Owner = "", Phone = "", Extensions = "519,520" },
             new Address { Id = 143, Name = "Eolo 44", Email = "", Owner = "", Phone = "", Extensions = "521,522" },
             new Address { Id = 144, Name = "Eolo 45", Email = "", Owner = "", Phone = "", Extensions = "523,524" },
             new Address { Id = 145, Name = "Eolo 46", Email = "", Owner = "", Phone = "", Extensions = "525,526" },
             new Address { Id = 146, Name = "Eolo 47", Email = "", Owner = "", Phone = "", Extensions = "527,528" },
             new Address { Id = 147, Name = "Eolo 49", Email = "", Owner = "", Phone = "", Extensions = "529,530" },
             new Address { Id = 148, Name = "Eolo 51", Email = "", Owner = "", Phone = "", Extensions = "531,532" },
             new Address { Id = 149, Name = "Eolo 53", Email = "", Owner = "", Phone = "", Extensions = "533,534" },
             new Address { Id = 150, Name = "Eolo 55", Email = "", Owner = "", Phone = "", Extensions = "535,536" },
             new Address { Id = 151, Name = "Eolo 57", Email = "", Owner = "", Phone = "", Extensions = "537,538" },
             new Address { Id = 152, Name = "Eolo 59", Email = "", Owner = "", Phone = "", Extensions = "539,540" },
             new Address { Id = 153, Name = "Eolo 61", Email = "", Owner = "", Phone = "", Extensions = "541,542" },
             new Address { Id = 154, Name = "Eolo 63", Email = "", Owner = "", Phone = "", Extensions = "543,544" },
             new Address { Id = 155, Name = "Eolo 65", Email = "", Owner = "", Phone = "", Extensions = "545,546" },
             new Address { Id = 156, Name = "Eolo 67", Email = "", Owner = "", Phone = "", Extensions = "547,548" },
             new Address { Id = 157, Name = "Eolo 69", Email = "", Owner = "", Phone = "", Extensions = "549,550" },
             new Address { Id = 158, Name = "Eolo 71", Email = "", Owner = "", Phone = "", Extensions = "551,552" },
             new Address { Id = 159, Name = "Eolo 73", Email = "", Owner = "", Phone = "", Extensions = "553,554" },
             new Address { Id = 160, Name = "Eolo 74", Email = "", Owner = "", Phone = "", Extensions = "555,556" },
             new Address { Id = 161, Name = "Eolo 75", Email = "", Owner = "", Phone = "", Extensions = "557,558" },
             new Address { Id = 162, Name = "Eolo 76", Email = "", Owner = "", Phone = "", Extensions = "559,560" },
             new Address { Id = 163, Name = "Eolo 78", Email = "", Owner = "", Phone = "", Extensions = "561,562" },
             new Address { Id = 164, Name = "Eolo 79", Email = "", Owner = "", Phone = "", Extensions = "563,564" },
             new Address { Id = 165, Name = "Eolo 80", Email = "", Owner = "", Phone = "", Extensions = "565,566,567" },
             new Address { Id = 166, Name = "Eolo 82", Email = "", Owner = "", Phone = "", Extensions = "568,569" },
             new Address { Id = 167, Name = "Eolo 84", Email = "", Owner = "", Phone = "", Extensions = "570,571" },
             new Address { Id = 168, Name = "Eolo 85", Email = "", Owner = "", Phone = "", Extensions = "572,573" },
             new Address { Id = 169, Name = "Eolo 86", Email = "", Owner = "", Phone = "", Extensions = "574,575" },
             new Address { Id = 170, Name = "Eolo 87", Email = "", Owner = "", Phone = "", Extensions = "576,577" },
             new Address { Id = 171, Name = "Eolo 88", Email = "", Owner = "", Phone = "", Extensions = "578,579" },
             new Address { Id = 172, Name = "Eolo 89", Email = "", Owner = "", Phone = "", Extensions = "580,581" },
             new Address { Id = 173, Name = "Eolo 90", Email = "", Owner = "", Phone = "", Extensions = "582,583" },
             new Address { Id = 174, Name = "Eolo 91", Email = "", Owner = "", Phone = "", Extensions = "584,585" },
             new Address { Id = 175, Name = "Eolo 92", Email = "", Owner = "", Phone = "", Extensions = "586,587" },
             new Address { Id = 176, Name = "Eolo 94", Email = "", Owner = "", Phone = "", Extensions = "588,589" },
             new Address { Id = 177, Name = "Eolo 96", Email = "", Owner = "", Phone = "", Extensions = "590,591" },
             new Address { Id = 178, Name = "Eolo 98", Email = "", Owner = "", Phone = "", Extensions = "592,593" },
             new Address { Id = 179, Name = "Eolo 100", Email = "", Owner = "", Phone = "", Extensions = "594,595" },
             new Address { Id = 180, Name = "Eolo 101", Email = "", Owner = "", Phone = "", Extensions = "596,597" },
             new Address { Id = 181, Name = "Eolo 103", Email = "", Owner = "", Phone = "", Extensions = "598,599" },
             new Address { Id = 182, Name = "Eolo 105", Email = "", Owner = "", Phone = "", Extensions = "600,601" },
             new Address { Id = 183, Name = "Godino 02", Email = "", Owner = "", Phone = "", Extensions = "" },
             new Address { Id = 184, Name = "Godino 04", Email = "", Owner = "", Phone = "", Extensions = "751,752" },
             new Address { Id = 185, Name = "Godino 06", Email = "", Owner = "", Phone = "", Extensions = "753,754" },
             new Address { Id = 186, Name = "Godino 08", Email = "", Owner = "", Phone = "", Extensions = "755,756" },
             new Address { Id = 187, Name = "Godino 10", Email = "", Owner = "", Phone = "", Extensions = "757,758" },
             new Address { Id = 188, Name = "Godino 12", Email = "", Owner = "", Phone = "", Extensions = "759,760" },
             new Address { Id = 189, Name = "Godino 14", Email = "", Owner = "", Phone = "", Extensions = "761,762" },
             new Address { Id = 190, Name = "Godino 16", Email = "", Owner = "", Phone = "", Extensions = "763,764,765" },
             new Address { Id = 191, Name = "Godino 18", Email = "", Owner = "", Phone = "", Extensions = "766,767" },
             new Address { Id = 192, Name = "Godino 20", Email = "", Owner = "", Phone = "", Extensions = "768,769" },
             new Address { Id = 193, Name = "Godino 22", Email = "", Owner = "", Phone = "", Extensions = "770,771" },
             new Address { Id = 194, Name = "Godino 24", Email = "", Owner = "", Phone = "", Extensions = "772,773" },
             new Address { Id = 195, Name = "Godino 26", Email = "", Owner = "", Phone = "", Extensions = "774,775" },
             new Address { Id = 196, Name = "Godino 28", Email = "", Owner = "", Phone = "", Extensions = "776,777" },
             new Address { Id = 197, Name = "Godino 30", Email = "", Owner = "", Phone = "", Extensions = "778,779" },
             new Address { Id = 198, Name = "Godino 32", Email = "", Owner = "", Phone = "", Extensions = "780,781" },
             new Address { Id = 199, Name = "Godino 34", Email = "", Owner = "", Phone = "", Extensions = "782,783" },
             new Address { Id = 200, Name = "Godino 36", Email = "", Owner = "", Phone = "", Extensions = "784,785" },
             new Address { Id = 201, Name = "Godino 38", Email = "", Owner = "", Phone = "", Extensions = "786,787" },
             new Address { Id = 202, Name = "Godino 40", Email = "", Owner = "", Phone = "", Extensions = "788,789" },
             new Address { Id = 203, Name = "Godino 42", Email = "", Owner = "", Phone = "", Extensions = "790,791" },
             new Address { Id = 204, Name = "Godino 44", Email = "", Owner = "", Phone = "", Extensions = "792,793" },
             new Address { Id = 205, Name = "Pavero 16", Email = "", Owner = "", Phone = "", Extensions = "910,911" },
             new Address { Id = 206, Name = "Pavero 18", Email = "", Owner = "", Phone = "", Extensions = "912,913" },
             new Address { Id = 207, Name = "Pavero 20", Email = "", Owner = "", Phone = "", Extensions = "914,915" },
             new Address { Id = 208, Name = "Navalon 01", Email = "", Owner = "", Phone = "", Extensions = "878,879" },
             new Address { Id = 209, Name = "Navalon 03", Email = "", Owner = "", Phone = "", Extensions = "880,881" },
             new Address { Id = 210, Name = "Navalon 05", Email = "", Owner = "", Phone = "", Extensions = "882,883" },
             new Address { Id = 211, Name = "Navalon 07", Email = "", Owner = "", Phone = "", Extensions = "884,885" },
             new Address { Id = 212, Name = "Galibi 01", Email = "", Owner = "", Phone = "", Extensions = "623,624" },
             new Address { Id = 213, Name = "Galibi 03", Email = "", Owner = "", Phone = "", Extensions = "625,626" },
             new Address { Id = 214, Name = "Barahona 01", Email = "", Owner = "", Phone = "", Extensions = "368,369" },
             new Address { Id = 215, Name = "Barahona 02", Email = "", Owner = "", Phone = "", Extensions = "370,371" },
             new Address { Id = 216, Name = "Barahona 03", Email = "", Owner = "", Phone = "", Extensions = "372,373" },
             new Address { Id = 217, Name = "Barahona 04", Email = "", Owner = "", Phone = "", Extensions = "374,375" },
             new Address { Id = 218, Name = "Tabor 19", Email = "", Owner = "", Phone = "", Extensions = "932,933,934" },
             new Address { Id = 219, Name = "Tabor 21", Email = "", Owner = "", Phone = "", Extensions = "935,936" },
             new Address { Id = 220, Name = "Tabor 23", Email = "", Owner = "", Phone = "", Extensions = "937,938" },
             new Address { Id = 221, Name = "Tabor 25", Email = "", Owner = "", Phone = "", Extensions = "939,940" },
             new Address { Id = 222, Name = "Tabor 27", Email = "", Owner = "", Phone = "", Extensions = "941,942" },
             new Address { Id = 223, Name = "Tabor 29", Email = "", Owner = "", Phone = "", Extensions = "943,944" },
             new Address { Id = 224, Name = "Tabor 31", Email = "", Owner = "", Phone = "", Extensions = "945,946" },
             new Address { Id = 225, Name = "Tabor 33", Email = "", Owner = "", Phone = "", Extensions = "947,948" },
             new Address { Id = 226, Name = "Tabor 35", Email = "", Owner = "", Phone = "", Extensions = "949,950" },
             new Address { Id = 227, Name = "Tabor 37", Email = "", Owner = "", Phone = "", Extensions = "951,952" },
             new Address { Id = 228, Name = "Tabor 39", Email = "", Owner = "", Phone = "", Extensions = "953,954" },
             new Address { Id = 229, Name = "Tabor 41", Email = "", Owner = "", Phone = "", Extensions = "955,956" },
             new Address { Id = 230, Name = "Tabor 43", Email = "", Owner = "", Phone = "", Extensions = "957,958" },
             new Address { Id = 231, Name = "Tabor 45", Email = "", Owner = "", Phone = "", Extensions = "959,960" },
             new Address { Id = 232, Name = "Tabor 47", Email = "", Owner = "", Phone = "", Extensions = "961,962" },
             new Address { Id = 233, Name = "Tabor 49", Email = "", Owner = "", Phone = "", Extensions = "963,964" },
             new Address { Id = 234, Name = "Credos 01", Email = "", Owner = "", Phone = "", Extensions = "392,393" },
             new Address { Id = 235, Name = "Credos 03", Email = "", Owner = "", Phone = "", Extensions = "394,395" },
             new Address { Id = 236, Name = "Credos 05", Email = "", Owner = "", Phone = "", Extensions = "396,397" },
             new Address { Id = 237, Name = "Credos 07", Email = "", Owner = "", Phone = "", Extensions = "398,399" },
             new Address { Id = 238, Name = "Credos 09", Email = "", Owner = "", Phone = "", Extensions = "400,401" },
             new Address { Id = 239, Name = "Credos 11", Email = "", Owner = "", Phone = "", Extensions = "402,403" },
             new Address { Id = 240, Name = "Credos 13", Email = "", Owner = "", Phone = "", Extensions = "404,405" },
             new Address { Id = 241, Name = "Credos 15", Email = "", Owner = "", Phone = "", Extensions = "406,407" },
             new Address { Id = 242, Name = "Credos 17", Email = "", Owner = "", Phone = "", Extensions = "408,409" },
             new Address { Id = 243, Name = "Credos 19", Email = "", Owner = "", Phone = "", Extensions = "410,411" },
             new Address { Id = 244, Name = "Credos 21", Email = "", Owner = "", Phone = "", Extensions = "412,413" },
             new Address { Id = 245, Name = "Credos 23", Email = "", Owner = "", Phone = "", Extensions = "414,415" },
             new Address { Id = 246, Name = "Credos 25", Email = "", Owner = "", Phone = "", Extensions = "416,417" },
             new Address { Id = 247, Name = "Credos 27", Email = "", Owner = "", Phone = "", Extensions = "418,419" },
             new Address { Id = 248, Name = "Credos 29", Email = "", Owner = "", Phone = "", Extensions = "420,421" },
             new Address { Id = 249, Name = "Credos 31", Email = "", Owner = "", Phone = "", Extensions = "422,423" },
             new Address { Id = 250, Name = "Credos 33", Email = "", Owner = "", Phone = "", Extensions = "424,425" },
             new Address { Id = 251, Name = "Credos 35", Email = "", Owner = "", Phone = "", Extensions = "426,427" },
             new Address { Id = 252, Name = "Credos 37", Email = "", Owner = "", Phone = "", Extensions = "428,429" },
             new Address { Id = 253, Name = "Credos 39", Email = "", Owner = "", Phone = "", Extensions = "430,431" },
             new Address { Id = 254, Name = "Credos 41", Email = "", Owner = "", Phone = "", Extensions = "432,433" },
             new Address { Id = 255, Name = "Avira 02", Email = "", Owner = "", Phone = "", Extensions = "318,319" },
             new Address { Id = 256, Name = "Avira 04", Email = "", Owner = "", Phone = "", Extensions = "320,321" },
             new Address { Id = 257, Name = "Avira 06", Email = "", Owner = "", Phone = "", Extensions = "322,323" },
             new Address { Id = 258, Name = "Avira 07", Email = "", Owner = "", Phone = "", Extensions = "324,325,326,327" },
             new Address { Id = 259, Name = "Avira 08", Email = "", Owner = "", Phone = "", Extensions = "328,329" },
             new Address { Id = 260, Name = "Avira 10", Email = "", Owner = "", Phone = "", Extensions = "330,331" },
             new Address { Id = 261, Name = "Avira 12", Email = "", Owner = "", Phone = "", Extensions = "332,333" },
             new Address { Id = 262, Name = "Avira 13", Email = "", Owner = "", Phone = "", Extensions = "334,335" },
             new Address { Id = 263, Name = "Avira 14", Email = "", Owner = "", Phone = "", Extensions = "336,337" },
             new Address { Id = 264, Name = "Avira 16", Email = "", Owner = "", Phone = "", Extensions = "338,339" },
             new Address { Id = 265, Name = "Avira 17", Email = "", Owner = "", Phone = "", Extensions = "340,341" },
             new Address { Id = 266, Name = "Avira 18", Email = "", Owner = "", Phone = "", Extensions = "342,343" },
             new Address { Id = 267, Name = "Avira 20", Email = "", Owner = "", Phone = "", Extensions = "344,345" },
             new Address { Id = 268, Name = "Avira 21", Email = "", Owner = "", Phone = "", Extensions = "346,347" },
             new Address { Id = 269, Name = "Avira 22", Email = "", Owner = "", Phone = "", Extensions = "348,349" },
             new Address { Id = 270, Name = "Avira 24", Email = "", Owner = "", Phone = "", Extensions = "350,351" },
             new Address { Id = 271, Name = "Avira 26", Email = "", Owner = "", Phone = "", Extensions = "352,353" },
             new Address { Id = 272, Name = "Avira 27", Email = "", Owner = "", Phone = "", Extensions = "354,355" },
             new Address { Id = 273, Name = "Avira 28", Email = "", Owner = "", Phone = "", Extensions = "356,357" },
             new Address { Id = 274, Name = "Avira 30", Email = "", Owner = "", Phone = "", Extensions = "358,359" },
             new Address { Id = 275, Name = "Avira 32", Email = "", Owner = "", Phone = "", Extensions = "360,361" },
             new Address { Id = 276, Name = "Avira 33", Email = "", Owner = "", Phone = "", Extensions = "362,363" },
             new Address { Id = 277, Name = "Avira 34", Email = "", Owner = "", Phone = "", Extensions = "364,365" },
             new Address { Id = 278, Name = "Avira 35", Email = "", Owner = "", Phone = "", Extensions = "366,367" },
             new Address { Id = 279, Name = "Gravina 02", Email = "", Owner = "", Phone = "", Extensions = "803,804" },
             new Address { Id = 280, Name = "Gravina 04", Email = "", Owner = "", Phone = "", Extensions = "805,806" },
             new Address { Id = 281, Name = "Gravina 06", Email = "", Owner = "", Phone = "", Extensions = "807,808,809,810,811" },
             new Address { Id = 282, Name = "Gravina 08", Email = "", Owner = "", Phone = "", Extensions = "812,813" },
             new Address { Id = 283, Name = "Gravina 10", Email = "", Owner = "", Phone = "", Extensions = "814,815" },
             new Address { Id = 284, Name = "Gravina 12", Email = "", Owner = "", Phone = "", Extensions = "816,817" },
             new Address { Id = 285, Name = "Gravina 14", Email = "", Owner = "", Phone = "", Extensions = "818,819" },
             new Address { Id = 286, Name = "Gravina 16", Email = "", Owner = "", Phone = "", Extensions = "820,821" },
             new Address { Id = 287, Name = "Gravina 18", Email = "", Owner = "", Phone = "", Extensions = "822,823" },
             new Address { Id = 288, Name = "Gravina 20", Email = "", Owner = "", Phone = "", Extensions = "824,825" },
             new Address { Id = 289, Name = "Gravina 22", Email = "", Owner = "", Phone = "", Extensions = "826,827" },
             new Address { Id = 290, Name = "Gravina 24", Email = "", Owner = "", Phone = "", Extensions = "828,829" },
             new Address { Id = 291, Name = "Gravina 26", Email = "", Owner = "", Phone = "", Extensions = "830,831" },
             new Address { Id = 292, Name = "Gravina 28", Email = "", Owner = "", Phone = "", Extensions = "832,833" },
             new Address { Id = 293, Name = "Gravina 30", Email = "", Owner = "", Phone = "", Extensions = "834,835" },
             new Address { Id = 294, Name = "Gravina 32", Email = "", Owner = "", Phone = "", Extensions = "836,837" },
             new Address { Id = 295, Name = "Gravina 34", Email = "", Owner = "", Phone = "", Extensions = "838,839" },
             new Address { Id = 296, Name = "Gravina 36", Email = "", Owner = "", Phone = "", Extensions = "840,841" },
             new Address { Id = 297, Name = "Gravina 38", Email = "", Owner = "", Phone = "", Extensions = "842,843" },
             new Address { Id = 298, Name = "Gravina 40", Email = "", Owner = "", Phone = "", Extensions = "844,845" },
             new Address { Id = 299, Name = "Gravina 42", Email = "", Owner = "", Phone = "", Extensions = "846,847" },
             new Address { Id = 300, Name = "Gravina 44", Email = "", Owner = "", Phone = "", Extensions = "848,849" },
             new Address { Id = 301, Name = "Gravina 46", Email = "", Owner = "", Phone = "", Extensions = "850,851" },
             new Address { Id = 302, Name = "Gravina 48", Email = "", Owner = "", Phone = "", Extensions = "852,853" },
             new Address { Id = 303, Name = "Gravina 50", Email = "", Owner = "", Phone = "", Extensions = "854,855" },
             new Address { Id = 304, Name = "Gravina 52", Email = "", Owner = "", Phone = "", Extensions = "856,857" }
        };
        streetNumbers = streetNumbers.Where(x => x.Name.Contains(selectedStreet)).ToList();
        //Task task = GetCards(selectedStreet);
        //task.Wait();
    }

    private async Task GetCards(string selectedStreet)
    {
       
        List<Cards> allCards = null;
        try
        {
            HttpResponseMessage response = await _httpClient.GetAsync("https://aaronisaacm.free.beeceptor.com/GetAllCards");
            if (response.IsSuccessStatusCode)
            {

                var content = await response.Content.ReadAsStringAsync();
                var resp = JsonConvert.DeserializeObject<List<Cards>>(content);
                allCards = resp.Where(x => x.Name == selectedStreet).ToList();

                foreach (var card in allCards)
                {
                    string cardsNum = "";
                    var selected = streetNumbers.Where(x => x.Name == card.Name);

                    foreach (var item in selected)
                    {
                        cardsNum = cardsNum + ", " + item;
                    }

                    streetNumbers.SingleOrDefault().Extensions = streetNumbers.SingleOrDefault().Extensions + " " + "Cards: " + cardsNum;
                }
            }
            else
            {

            }
        }
        catch (Exception ex)
        {
            string error = ex.Message;
        }
    }
}

